### PR TITLE
Move the current API to v1.

### PR DESCRIPTION
**Pull request by DeKleineKobini**
Make the API work with versions.

### CODE REVIEW

**Comment by DeKleineKobini** [comment]
@Llyfrs To avoid breaking changes (like possibly in #123), I want to make it work with versions.

You can try it [here](https://vercel.live/link/tornapi-documentation-git-feature-api-version-torn-playground.vercel.app?via=deployment-domains-list-branch).

**Comment by Llyfrs** [comment]
Seems to return empty structures right now lol. But I like the versions idea!

**Comment by DeKleineKobini** [comment]
> Seems to return empty structures right now lol. But I like the versions idea!

Forgot to replace the `return []` with my mapper xD

**Comment by DeKleineKobini** [comment]
> Seems to return empty structures right now lol. But I like the versions idea!

If it's okay for you, I'll merge this tomorrow or Friday. Besides the url change, I don't think anything else changed.

**Comment by Llyfrs** [comment]
> > Seems to return empty structures right now lol. But I like the versions idea!
> 
> If it's okay for you, I'll merge this tomorrow or Friday. Besides the url change, I don't think anything else changed.

Looks all good to me.

**Pull request merged**
