### PR TITLE
Added /api route, exporting api schemas programmatically

### PR DESCRIPTION
**Pull request by MCSH**

### CODE REVIEW

**Review by DeKleineKobini — CHANGES_REQUESTED** [review]
Along with the above comment, also make sure to pull my main branch. I've updated some linting rules because they were too strict for a NextJS application.

**Comment by DeKleineKobini** [comment]
Currently the endpoints are
`GET /api` and `GET /api/{section}`, but I do think that `GET /sections` and `GET /api/schema/{section}` would be better.

**Review by DeKleineKobini — CHANGES_REQUESTED** [review]
Currently the endpoints are
`GET /api` and `GET /api/{section}`, but I do think that `GET /sections` and `GET /api/schema/{section}` would be better.

**Comment by MCSH** [comment]
> Currently the endpoints are `GET /api` and `GET /api/{section}`, but I do think that `GET /sections` and `GET /api/schema/{section}` would be better.

Yes, even omitting the `/sections` entirely might not be a bad idea. I just jotted down some code to make a working version.

By the way feel free to modify them as you see fit, I haven't used these in my projects yet and it would be a while until I d. Unfortunately I won't be able to allocate more time at this moment.

**Comment by DeKleineKobini** [comment]
Closing in favor of #100

**Pull request closed without merging**
